In [1]:
# Importing the libraries needed

import numpy as np
import matplotlib as plt
import pandas as pd

In [2]:
# Load the dataset for analysis

CMS_calori_dataset = pd.read_csv('hgcal.csv')

CMS_calori_dataset.head(n = 10)

,Unnamed: 0,x,y,z,eta,phi,energy,trackId
0,0,179.50383,-23.632137,-7.878280,-0.0435,-0.130900,0.200126,462412
1,1,-143.63881,110.217940,-72.706795,-0.3915,2.487094,2.734594,493395
2,2,179.50383,-23.632120,-146.429610,-0.7395,-0.130900,0.423910,1
3,3,-172.67310,54.443620,-238.065340,-1.0875,2.836160,0.713950,493640
4,4,-180.88046,7.897389,-238.065340,-1.0875,3.097959,0.000000,495225
5,5,-180.88045,-7.897438,-238.065340,-1.0875,-3.097959,0.034491,495225
6,6,-152.69838,-97.279590,-265.020540,-1.1745,-2.574361,0.580138,460126
7,7,-23.63213,179.503810,-325.172060,-1.3485,1.701696,0.411487,465028
8,8,-152.69835,97.279594,89.977780,0.4785,2.574361,0.183141,1383
9,9,-176.76110,39.187016,107.930240,0.5655,2.923426,0.337551,4421

In [4]:
# Converting the dataset to an array that can be worked in numpy
CMS_calori_dataset_np = CMS_calori_dataset.to_numpy()

#Showing the new array dimensions
print(CMS_calori_dataset_np.shape)

(420, 8)

In [25]:
# Slicing the array for those specific columns
CMS_calori_dataset_np_sub = CMS_calori_dataset_np[:, 1:7]

# Printing the first row to show that I have the correct columns extracted
print(CMS_calori_dataset_np_sub[0])

[ 1.7950383e+02 -2.3632137e+01 -7.8782797e+00 -4.3500002e-02
 -1.3089974e-01  2.0012644e-01]

In [ ]:
def scale_data(arr):
    x = 
    mean = 
    std_dv = 
    return scaled_data